language: perl

sudo: false

perl:
    - "5.26"

addons:
    apt:
        packages:
            - pigz
            - unzip
            - libstdc++6
            - liblzma5
            - libbz2-1.0
            - zlib1g-dev
            
install:
    - "export PATH=$PWD/.travis:$PWD/bin:$PATH"
    - "mkdir -p deps && cd deps && source install_deps.sh && cd .."
    - "pwd"
    - "echo $HOME"
    - "echo $PATH"
    - "find deps -executable -type f"

script:
    - "kmc"
    - "skesa --version"
    - "shovill --version"
    - "shovill --check"
    - "shovill --help"
    - "! shovill --doesnotexist"
    - "shovill --outdir out.spades --assembler spades --R1 test/R1.fq.gz --R2 test/R2.fq.gz --nostitch --noreadcorr --nocorr"
    - "grep '>' out.spades/contigs.fa"
    - "shovill --outdir out.megahit --assembler megahit --R1 test/R1.fq.gz --R2 test/R2.fq.gz --trim"
    - "grep '>' out.megahit/contigs.fa"
    - "shovill --outdir out.velvet --assembler velvet --R1 test/R1.fq.gz --R2 test/R2.fq.gz --ram 4 --noreadcorr --nocorr"
    - "grep '>' out.velvet/contigs.fa"
